### ISSUE TITLE
Autocomplete issues

### ISSUE THREAD

**Issue by racecraftr** [neoclide/coc-java#233] opened 2023-01-13 02:30 UTC
The language server has two main issues, in my opinion:

1) Whenever i use the `sout~` completion, it always adds an extra "S" to the start - resulting in `SSystem.out.println`. 
2) Say that I have a class like this:
```java
class Foo {
}

```
I want to add a new line to write code inside the class, so I go to the left curly brace `{` and hit enter. But for some reason, this is what the extension does: 
```java
class Foo{

}
}
```
again, very annoying. (This also happens for functions, by the way.)
Is there any way to fix this?

**Comment by chemzqm** [comment] 2023-01-23 07:32
Can't reproduce any of them, try upgrade your coc.nvim and use minimal vimrc.

**Comment by Taz03** [comment] 2023-01-25 21:30
the first one happens for me as well, and i have no idea y

**Comment by chemzqm** [comment] 2023-01-27 00:10
> the first one happens for me as well, and i have no idea y

Fixed on latest release branch of coc.nvim.

**Comment by chemzqm** [comment] 2023-01-28 19:26
For second issue, please try minimal vimrc.

**Closed by chemzqm** 2023-01-28 19:26 UTC
Labels: Cant' reproduce
